# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - asma

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write        # requerido para azure/login
      contents: read         # requerido para checkout

    steps:
      # 1) Traer el código del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Configurar Node
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      # 3) Instalar dependencias y build dentro de Backend/node
      - name: npm install, build, and test
        working-directory: Backend/node
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # 4) Login a Azure con la identidad que te generó el Deployment Center
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_03F5194685D64BC5A57B84174A8C9E84 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D5C7136E29184C469828E2B3071D1CA5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D4C7E0C5D8E34A5DA25EDE450898099D }}

      # 5) Desplegar la carpeta Backend/node al App Service "asma"
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'asma'
          slot-name: 'Production'
          package: Backend/node
